export const resourceFields = {
  raw_material_logs: [
    { name: 'supplier_name', label: 'Supplier Name', type: 'text', required: true },
    { name: 'agreed_scheduled_date', label: 'Agreed Scheduled Date', type: 'date', required: false },
    { name: 'receiving_date', label: 'Receiving Date', type: 'date', required: true },
    { name: 'time_received', label: 'Time Received', type: 'time', required: true },
    { name: 'delivery_vehicle_id', label: 'Delivery Vehicle ID', type: 'text', required: false },
    { name: 'qc_inspector', label: 'QC Inspector', type: 'text', required: true },
    { name: 'raw_material', label: 'Raw Material', type: 'text', required: true },
    { name: 'packaging_condition', label: 'Packaging Condition', type: 'select', options: ['GOOD', 'DAMAGED'], required: true },
    { name: 'moisture_content_or_expiry', label: 'Moisture / Expiry', type: 'text', required: false },
    { name: 'within_specs', label: 'Within Specs', type: 'checkbox', required: false },
    { name: 'quantity', label: 'Quantity', type: 'number', required: true },
    { name: 'status', label: 'Status', type: 'select', options: ['ACCEPTED', 'REJECTED'], required: true },
    { name: 'inspector_initials', label: 'Inspector Initials', type: 'text', required: true },
    { name: 'received_by', label: 'Received By', type: 'text', required: true },
  ],
  delivery_truck_logs: [
    { name: 'truck_plate_no', label: 'Truck Plate No', type: 'text', required: true },
    { name: 'driver_name', label: 'Driver Name', type: 'text', required: true },
    { name: 'checked_by', label: 'Checked By', type: 'text', required: true },
    { name: 'inspection_date', label: 'Inspection Date', type: 'date', required: true },
    { name: 'inspection_time', label: 'Inspection Time', type: 'time', required: true },
    { name: 'exterior_condition', label: 'Exterior Condition', type: 'select', options: ['CLEAN', 'DIRTY'], required: true },
    { name: 'interior_condition', label: 'Interior Condition', type: 'select', options: ['CLEAN', 'DIRTY'], required: true },
    { name: 'odor', label: 'Odor', type: 'select', options: ['NORMAL', 'UNUSUAL'], required: true },
    { name: 'pest_activity', label: 'Pest Activity', type: 'checkbox', required: false },
    { name: 'sanitized', label: 'Sanitized', type: 'checkbox', required: false },
    { name: 'maintenance_issues', label: 'Maintenance Issues', type: 'checkbox', required: false },
    { name: 'inspector_initials', label: 'Inspector Initials', type: 'text', required: true },
    { name: 'corrective_action', label: 'Corrective Action', type: 'textarea', required: false },
  ],
  pest_control_logs: [
    { name: 'inspection_date', label: 'Inspection Date', type: 'date', required: true },
    { name: 'inspector_name', label: 'Inspector Name', type: 'text', required: true },
    { name: 'inspection_area', label: 'Inspection Area', type: 'text', required: true },
    { name: 'pest_activity_observed', label: 'Pest Activity Observed', type: 'checkbox', required: false },
    { name: 'type_of_pest', label: 'Type of Pest', type: 'text', required: false },
    { name: 'corrective_action_taken', label: 'Corrective Action Taken', type: 'textarea', required: false },
    { name: 'inspector_initials', label: 'Inspector Initials', type: 'text', required: true },
    { name: 'verified_by_qa', label: 'Verified By QA', type: 'text', required: false },
  ],
  oil_temperature_logs: [
    { name: 'production_date', label: 'Production Date', type: 'date', required: true },
    { name: 'batch_lot_no', label: 'Batch / Lot No', type: 'text', required: true },
    { name: 'operator_name_id', label: 'Operator Name / ID', type: 'text', required: true },
    { name: 'time_checked', label: 'Time Checked', type: 'time', required: true },
    { name: 'oil_temperature_c', label: 'Oil Temperature (°C)', type: 'number', required: true },
    { name: 'operator_initial', label: 'Operator Initial', type: 'text', required: true },
    { name: 'corrective_action', label: 'Corrective Action', type: 'textarea', required: false },
    { name: 'verified_by_qa', label: 'Verified By QA', type: 'text', required: false },
  ],
  cleaning_logs: [
    { name: 'log_date', label: 'Log Date', type: 'date', required: true },
    { name: 'log_time', label: 'Log Time', type: 'time', required: true },
    { name: 'area_of_concern', label: 'Area of Concern', type: 'text', required: true },
    { name: 'standard_met', label: 'Standard Met', type: 'checkbox', required: false },
    { name: 'action_taken', label: 'Action Taken', type: 'textarea', required: false },
    { name: 'sanitizer_used', label: 'Sanitizer Used', type: 'text', required: false },
    { name: 'performed_by', label: 'Performed By', type: 'text', required: true },
    { name: 'checked_by', label: 'Checked By', type: 'text', required: false },
  ],
  stock_management_logs: [
    { name: 'warehouse_location', label: 'Warehouse Location', type: 'text', required: true },
    { name: 'checked_by', label: 'Checked By', type: 'text', required: true },
    { name: 'log_date', label: 'Log Date', type: 'date', required: true },
    { name: 'log_time', label: 'Log Time', type: 'time', required: true },
    { name: 'product_name', label: 'Product Name', type: 'text', required: true },
    { name: 'batch_lot_no', label: 'Batch / Lot No', type: 'text', required: true },
    { name: 'quantity_in_stock', label: 'Quantity In Stock', type: 'number', required: true },
    { name: 'expiry_date', label: 'Expiry Date', type: 'date', required: false },
    { name: 'storage_condition', label: 'Storage Condition', type: 'select', options: ['GOODS', 'NEEDS ATTENTION'], required: true },
    { name: 'fifo_fefo_followed', label: 'FIFO/FEFO Followed', type: 'checkbox', required: false },
    { name: 'inspector_initials', label: 'Inspector Initials', type: 'text', required: true },
    { name: 'corrective_action', label: 'Corrective Action', type: 'textarea', required: false },
  ],
};

export const resourceColumns = {
  raw_material_logs: [
    { key: 'supplier_name', label: 'Supplier' },
    { key: 'raw_material', label: 'Material' },
    { key: 'packaging_condition', label: 'Packaging' },
    { key: 'status', label: 'Status' },
    { key: 'receiving_date', label: 'Received' },
  ],
  delivery_truck_logs: [
    { key: 'truck_plate_no', label: 'Plate' },
    { key: 'driver_name', label: 'Driver' },
    { key: 'exterior_condition', label: 'Exterior' },
    { key: 'pest_activity', label: 'Pest' },
    { key: 'inspection_date', label: 'Date' },
  ],
  pest_control_logs: [
    { key: 'inspection_area', label: 'Area' },
    { key: 'inspector_name', label: 'Inspector' },
    { key: 'pest_activity_observed', label: 'Activity' },
    { key: 'inspection_date', label: 'Date' },
  ],
  oil_temperature_logs: [
    { key: 'batch_lot_no', label: 'Batch' },
    { key: 'oil_temperature_c', label: 'Temp (°C)' },
    { key: 'operator_name_id', label: 'Operator' },
    { key: 'production_date', label: 'Date' },
  ],
  cleaning_logs: [
    { key: 'area_of_concern', label: 'Area' },
    { key: 'performed_by', label: 'Performed By' },
    { key: 'standard_met', label: 'Standard Met' },
    { key: 'log_date', label: 'Date' },
  ],
  stock_management_logs: [
    { key: 'product_name', label: 'Product' },
    { key: 'batch_lot_no', label: 'Batch' },
    { key: 'storage_condition', label: 'Storage' },
    { key: 'quantity_in_stock', label: 'Qty' },
    { key: 'log_date', label: 'Date' },
  ],
};

export const resourceMeta = {
  raw_material_logs: { title: 'Raw Material Logs', path: '/raw-material-logs' },
  delivery_truck_logs: { title: 'Delivery Truck Logs', path: '/delivery-truck-logs' },
  pest_control_logs: { title: 'Pest Control Logs', path: '/pest-control-logs' },
  oil_temperature_logs: { title: 'Oil Temperature Logs', path: '/oil-temperature-logs' },
  cleaning_logs: { title: 'Cleaning Logs', path: '/cleaning-logs' },
  stock_management_logs: { title: 'Stock Management Logs', path: '/stock-management-logs' },
};
